ci(sonar-backend): séparer scan Sonar push/PR + ajouter props PR + fix config 2

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -209,14 +209,14 @@ jobs:
       - name: SonarCloud scan (backend - PR)
         if: ${{ github.event_name == 'pull_request' }}
         env: ${{ secrets.SONAR_TOKEN }}
-        run: |    
-         BASE="${{ github.workspace }}/mateleau-crm-backend"
-         REPORT="$BASE/coverage/lcov.info"
-         echo "BASE=$BASE"
-         test -f "$REPORT" || (echo "Missing $REPORT" && exit 1)
-         wc -c "$REPORT" || true
-         echo "Using coverage: $REPORT"
-         sonar-scanner \
+        run: |
+          BASE="${{ github.workspace }}/mateleau-crm-backend"
+          REPORT="$BASE/coverage/lcov.info"
+          echo "BASE=$BASE"
+          test -f "$REPORT" || (echo "Missing $REPORT" && exit 1)
+          wc -c "$REPORT" || true
+          echo "Using coverage: $REPORT"
+          sonar-scanner \
             -Dsonar.projectKey=crm-mateleau-backend \
             -Dsonar.organization=elluco6 \
             -Dsonar.host.url=https://sonarcloud.io \
